{
  imports = [
    ./keymaps/buffers.nix
    ./keymaps/copy_location.nix
    ./keymaps/git.nix
    ./keymaps/incremental_selection.nix
    ./keymaps/join_split.nix
    ./keymaps/location_list.nix
    ./keymaps/lsp.nix
    ./keymaps/navigation.nix
    ./keymaps/oil.nix
    ./keymaps/quickfix_list.nix
    ./keymaps/search.nix
    ./keymaps/sidekick.nix
    ./keymaps/snacks.nix
    ./keymaps/tabs.nix
    ./keymaps/treesitter_textobjects.nix
    ./keymaps/undotree.nix
    ./keymaps/window_management.nix
  ];
}
