{
  imports = [
    ./abolish.nix
    ./blink.nix
    ./builtin.nix
    ./conform.nix
    ./context.nix
    ./dap.nix
    ./go.nix
    ./lint.nix
    ./lsp.nix
    ./lualine.nix
    ./mini.nix
    ./neotest.nix
    ./oil.nix
    ./overseer.nix
    ./render-markdown.nix
    ./schemastore.nix
    ./sidekick.nix
    ./sleuth.nix
    ./snacks.nix
    ./textobj.nix
    ./theme.nix
    ./treesitter.nix
    ./treesj.nix
    ./vtsls.nix
  ];
}
